[package]
name = "mock_offchain"
version = "0.1.0"
edition = "2024"

[dependencies]
borsh = "=0.10.4"
solana-client = "2.1.0"
solana-program = "2.1.0"
solana-sdk  = "2.1.0"
solana-transaction-status = "2.1.0"